language: java

before_install:
  - pwd
  - "ls -la"
  - chmod 777 ./src/test/resources/drivers/chromedriver.exe
  - chmod 777 ./target/test-classes/drivers/chromedriver.exe
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - "mvn verify"
#script: ./mvnw clean install
#before_script:
#  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
#  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
#  - export CHROME_BIN=chromium-browser
#script:
#- "mvn compile"